USE ROLE ACCOUNTADMIN;

-- Create Git-API Integration
CREATE OR REPLACE ROLE SNOWFLAKE_DEMO_HUB;
GRANT ROLE SNOWFLAKE_DEMO_HUB TO USER ADMIN;

CREATE OR REPLACE API INTEGRATION GITHUB_INTEGRATION
    api_provider = git_https_api
    api_allowed_prefixes = ('https://github.com/')
    enabled = true
    comment='General Git-Integration';

-- Create a warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE='X-SMALL';

-- Grants to demo role
GRANT USAGE ON INTEGRATION GITHUB_INTEGRATION TO ROLE SNOWFLAKE_DEMO_HUB;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SNOWFLAKE_DEMO_HUB;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SNOWFLAKE_DEMO_HUB;
GRANT OPERATE, USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SNOWFLAKE_DEMO_HUB;

-- Setup App
USE ROLE SNOWFLAKE_DEMO_HUB;